package com.yiguo.bean;

import java.io.Serializable;
import java.util.Date;

/**
 * 
 * answer实体类
 * 
 * @author liyue
 * @date 2018-01-23
 */
public class Answer implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column answer.id
	 *
	 * @mbggenerated
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column answer.question_id
	 *
	 * @mbggenerated
	 */
	private Integer questionId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column answer.context
	 *
	 * @mbggenerated
	 */
	private String context;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column answer.user_id
	 *
	 * @mbggenerated
	 */
	private Integer userId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column answer.time
	 *
	 * @mbggenerated
	 */
	private Date time;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column answer.create_time
	 *
	 * @mbggenerated
	 */
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column answer.update_time
	 *
	 * @mbggenerated
	 */
	private Date updateTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table answer
	 *
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column answer.id
	 *
	 * @return the value of answer.id
	 *
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column answer.id
	 *
	 * @param id
	 *            the value for answer.id
	 *
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column answer.question_id
	 *
	 * @return the value of answer.question_id
	 *
	 * @mbggenerated
	 */
	public Integer getQuestionId() {
		return questionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column answer.question_id
	 *
	 * @param questionId
	 *            the value for answer.question_id
	 *
	 * @mbggenerated
	 */
	public void setQuestionId(Integer questionId) {
		this.questionId = questionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column answer.context
	 *
	 * @return the value of answer.context
	 *
	 * @mbggenerated
	 */
	public String getContext() {
		return context;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column answer.context
	 *
	 * @param context
	 *            the value for answer.context
	 *
	 * @mbggenerated
	 */
	public void setContext(String context) {
		this.context = context == null ? null : context.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column answer.user_id
	 *
	 * @return the value of answer.user_id
	 *
	 * @mbggenerated
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column answer.user_id
	 *
	 * @param userId
	 *            the value for answer.user_id
	 *
	 * @mbggenerated
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column answer.time
	 *
	 * @return the value of answer.time
	 *
	 * @mbggenerated
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column answer.time
	 *
	 * @param time
	 *            the value for answer.time
	 *
	 * @mbggenerated
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column answer.create_time
	 *
	 * @return the value of answer.create_time
	 *
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column answer.create_time
	 *
	 * @param createTime
	 *            the value for answer.create_time
	 *
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column answer.update_time
	 *
	 * @return the value of answer.update_time
	 *
	 * @mbggenerated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column answer.update_time
	 *
	 * @param updateTime
	 *            the value for answer.update_time
	 *
	 * @mbggenerated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table answer
	 *
	 * @mbggenerated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		Answer other = (Answer) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getQuestionId() == null ? other.getQuestionId() == null
						: this.getQuestionId().equals(other.getQuestionId()))
				&& (this.getContext() == null ? other.getContext() == null
						: this.getContext().equals(other.getContext()))
				&& (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
				&& (this.getTime() == null ? other.getTime() == null : this.getTime().equals(other.getTime()))
				&& (this.getCreateTime() == null ? other.getCreateTime() == null
						: this.getCreateTime().equals(other.getCreateTime()))
				&& (this.getUpdateTime() == null ? other.getUpdateTime() == null
						: this.getUpdateTime().equals(other.getUpdateTime()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table answer
	 *
	 * @mbggenerated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getQuestionId() == null) ? 0 : getQuestionId().hashCode());
		result = prime * result + ((getContext() == null) ? 0 : getContext().hashCode());
		result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
		result = prime * result + ((getTime() == null) ? 0 : getTime().hashCode());
		result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
		result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table answer
	 *
	 * @mbggenerated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", questionId=").append(questionId);
		sb.append(", context=").append(context);
		sb.append(", userId=").append(userId);
		sb.append(", time=").append(time);
		sb.append(", createTime=").append(createTime);
		sb.append(", updateTime=").append(updateTime);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}