package com.yiguo.bean;

import java.io.Serializable;
import java.util.Date;

/**
 * 
 * Enterprise实体类
 * 
 * @author liyue
 * @date 2018-01-23
 */
public class Enterprise implements Serializable {
	private Integer id;

	private String name;
	private String userName;
	private String userPassword;
	private String email;

	private String address;

	private String linkman;
	private String phone;
	private Integer industryId;

	private Integer zoneId;

	private Date createTime;
	private Date updateTime;

	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column enterprise.id
	 *
	 * @return the value of enterprise.id
	 *
	 * @mbggenerated
	 */
	private Integer state;
	private String imageLog;
	private String imageLicense;
	private String description;
	private Integer stage;

	public Integer getState() {
		return state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	public String getImageLog() {
		return imageLog;
	}

	public void setImageLog(String imageLog) {
		this.imageLog = imageLog;
	}

	public String getImageLicense() {
		return imageLicense;
	}

	public void setImageLicense(String imageLicense) {
		this.imageLicense = imageLicense;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getStage() {
		return stage;
	}

	public void setStage(Integer stage) {
		this.stage = stage;
	}

	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column enterprise.id
	 *
	 * @param id
	 *            the value for enterprise.id
	 *
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column enterprise.name
	 *
	 * @return the value of enterprise.name
	 *
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column enterprise.name
	 *
	 * @param name
	 *            the value for enterprise.name
	 *
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column enterprise.user_name
	 *
	 * @return the value of enterprise.user_name
	 *
	 * @mbggenerated
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column enterprise.user_name
	 *
	 * @param userName
	 *            the value for enterprise.user_name
	 *
	 * @mbggenerated
	 */
	public void setUserName(String userName) {
		this.userName = userName == null ? null : userName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column enterprise.user_password
	 *
	 * @return the value of enterprise.user_password
	 *
	 * @mbggenerated
	 */
	public String getUserPassword() {
		return userPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column enterprise.user_password
	 *
	 * @param userPassword
	 *            the value for enterprise.user_password
	 *
	 * @mbggenerated
	 */
	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword == null ? null : userPassword.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column enterprise.email
	 *
	 * @return the value of enterprise.email
	 *
	 * @mbggenerated
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column enterprise.email
	 *
	 * @param email
	 *            the value for enterprise.email
	 *
	 * @mbggenerated
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column enterprise.address
	 *
	 * @return the value of enterprise.address
	 *
	 * @mbggenerated
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column enterprise.address
	 *
	 * @param address
	 *            the value for enterprise.address
	 *
	 * @mbggenerated
	 */
	public void setAddress(String address) {
		this.address = address == null ? null : address.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column enterprise.linkman
	 *
	 * @return the value of enterprise.linkman
	 *
	 * @mbggenerated
	 */
	public String getLinkman() {
		return linkman;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column enterprise.linkman
	 *
	 * @param linkman
	 *            the value for enterprise.linkman
	 *
	 * @mbggenerated
	 */
	public void setLinkman(String linkman) {
		this.linkman = linkman == null ? null : linkman.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column enterprise.phone
	 *
	 * @return the value of enterprise.phone
	 *
	 * @mbggenerated
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column enterprise.phone
	 *
	 * @param phone
	 *            the value for enterprise.phone
	 *
	 * @mbggenerated
	 */
	public void setPhone(String phone) {
		this.phone = phone == null ? null : phone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column enterprise.industry_id
	 *
	 * @return the value of enterprise.industry_id
	 *
	 * @mbggenerated
	 */
	public Integer getIndustryId() {
		return industryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column enterprise.industry_id
	 *
	 * @param industryId
	 *            the value for enterprise.industry_id
	 *
	 * @mbggenerated
	 */
	public void setIndustryId(Integer industryId) {
		this.industryId = industryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column enterprise.zone_id
	 *
	 * @return the value of enterprise.zone_id
	 *
	 * @mbggenerated
	 */
	public Integer getZoneId() {
		return zoneId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column enterprise.zone_id
	 *
	 * @param zoneId
	 *            the value for enterprise.zone_id
	 *
	 * @mbggenerated
	 */
	public void setZoneId(Integer zoneId) {
		this.zoneId = zoneId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column enterprise.create_time
	 *
	 * @return the value of enterprise.create_time
	 *
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column enterprise.create_time
	 *
	 * @param createTime
	 *            the value for enterprise.create_time
	 *
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column enterprise.update_time
	 *
	 * @return the value of enterprise.update_time
	 *
	 * @mbggenerated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column enterprise.update_time
	 *
	 * @param updateTime
	 *            the value for enterprise.update_time
	 *
	 * @mbggenerated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table enterprise
	 *
	 * @mbggenerated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		Enterprise other = (Enterprise) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
				&& (this.getUserName() == null ? other.getUserName() == null
						: this.getUserName().equals(other.getUserName()))
				&& (this.getUserPassword() == null ? other.getUserPassword() == null
						: this.getUserPassword().equals(other.getUserPassword()))
				&& (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
				&& (this.getAddress() == null ? other.getAddress() == null
						: this.getAddress().equals(other.getAddress()))
				&& (this.getLinkman() == null ? other.getLinkman() == null
						: this.getLinkman().equals(other.getLinkman()))
				&& (this.getPhone() == null ? other.getPhone() == null : this.getPhone().equals(other.getPhone()))
				&& (this.getIndustryId() == null ? other.getIndustryId() == null
						: this.getIndustryId().equals(other.getIndustryId()))
				&& (this.getZoneId() == null ? other.getZoneId() == null : this.getZoneId().equals(other.getZoneId()))
				&& (this.getCreateTime() == null ? other.getCreateTime() == null
						: this.getCreateTime().equals(other.getCreateTime()))
				&& (this.getUpdateTime() == null ? other.getUpdateTime() == null
						: this.getUpdateTime().equals(other.getUpdateTime()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table enterprise
	 *
	 * @mbggenerated
	 */
	@Override
	public int hashCode() {
		final Integer prime = 31;
		Integer result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
		result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
		result = prime * result + ((getUserPassword() == null) ? 0 : getUserPassword().hashCode());
		result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
		result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
		result = prime * result + ((getLinkman() == null) ? 0 : getLinkman().hashCode());
		result = prime * result + ((getPhone() == null) ? 0 : getPhone().hashCode());
		result = prime * result + ((getIndustryId() == null) ? 0 : getIndustryId().hashCode());
		result = prime * result + ((getZoneId() == null) ? 0 : getZoneId().hashCode());
		result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
		result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
		return result;
	}

	@Override
	public String toString() {
		return "Enterprise [id=" + id + ", name=" + name + ", userName=" + userName + ", userPassword=" + userPassword
				+ ", email=" + email + ", address=" + address + ", linkman=" + linkman + ", phone=" + phone
				+ ", industryId=" + industryId + ", zoneId=" + zoneId + ", createTime=" + createTime + ", updateTime="
				+ updateTime + ", state=" + state + ", imageLog=" + imageLog + ", imageLicense=" + imageLicense
				+ ", description=" + description + ", stage=" + stage + "]";
	}

	
}