package com.yiguo.bean;

import java.io.Serializable;
import java.util.Date;

/**
 * 
 * Job实体类
 * 
 * @author liyue
 * @date 2018-01-23
 */
public class Job implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column job.id
	 *
	 * @mbggenerated
	 */
	private Integer id;
    private Integer state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column job.enterprise_id
	 *
	 * @mbggenerated
	 */
	private Integer enterpriseId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column job.title
	 *
	 * @mbggenerated
	 */
	private String title;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column job.nature
	 *
	 * @mbggenerated
	 */
	private String nature;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column job.industry_id
	 *
	 * @mbggenerated
	 */
	private Integer industryId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column job.zone_id
	 *
	 * @mbggenerated
	 */
	private Integer zoneId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column job.address
	 *
	 * @mbggenerated
	 */
	private String address;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column job.effective_time
	 *
	 * @mbggenerated
	 */
	private Date effectiveTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column job.expiration_time
	 *
	 * @mbggenerated
	 */
	private Date expirationTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column job.wage
	 *
	 * @mbggenerated
	 */
	private Integer wage;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column job.people_number
	 *
	 * @mbggenerated
	 */
	private Integer peopleNumber;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column job.education
	 *
	 * @mbggenerated
	 */
	private String education;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column job.service_year
	 *
	 * @mbggenerated
	 */
	private String serviceYear;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column job.description
	 *
	 * @mbggenerated
	 */
	private String description;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column job.welfare
	 *
	 * @mbggenerated
	 */
	private String welfare;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column job.email
	 *
	 * @mbggenerated
	 */
	private String email;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column job.creat_time
	 *
	 * @mbggenerated
	 */
	private Date creatTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column job.update_time
	 *
	 * @mbggenerated
	 */
	private Date updateTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table job
	 *
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column job.id
	 *
	 * @return the value of job.id
	 *
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column job.id
	 *
	 * @param id
	 *            the value for job.id
	 *
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column job.enterprise_id
	 *
	 * @return the value of job.enterprise_id
	 *
	 * @mbggenerated
	 */
	public Integer getEnterpriseId() {
		return enterpriseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column job.enterprise_id
	 *
	 * @param enterpriseId
	 *            the value for job.enterprise_id
	 *
	 * @mbggenerated
	 */
	public void setEnterpriseId(Integer enterpriseId) {
		this.enterpriseId = enterpriseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column job.title
	 *
	 * @return the value of job.title
	 *
	 * @mbggenerated
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column job.title
	 *
	 * @param title
	 *            the value for job.title
	 *
	 * @mbggenerated
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column job.nature
	 *
	 * @return the value of job.nature
	 *
	 * @mbggenerated
	 */
	public String getNature() {
		return nature;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column job.nature
	 *
	 * @param nature
	 *            the value for job.nature
	 *
	 * @mbggenerated
	 */
	public void setNature(String nature) {
		this.nature = nature == null ? null : nature.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column job.industry_id
	 *
	 * @return the value of job.industry_id
	 *
	 * @mbggenerated
	 */
	public Integer getIndustryId() {
		return industryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column job.industry_id
	 *
	 * @param industryId
	 *            the value for job.industry_id
	 *
	 * @mbggenerated
	 */
	public void setIndustryId(Integer industryId) {
		this.industryId = industryId;
	}

    public Integer getState() {
        return state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

    /**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column job.zone_id
	 *
	 * @return the value of job.zone_id
	 *
	 * @mbggenerated
	 */
	public Integer getZoneId() {
		return zoneId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column job.zone_id
	 *
	 * @param zoneId
	 *            the value for job.zone_id
	 *
	 * @mbggenerated
	 */
	public void setZoneId(Integer zoneId) {
		this.zoneId = zoneId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column job.address
	 *
	 * @return the value of job.address
	 *
	 * @mbggenerated
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column job.address
	 *
	 * @param address
	 *            the value for job.address
	 *
	 * @mbggenerated
	 */
	public void setAddress(String address) {
		this.address = address == null ? null : address.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column job.effective_time
	 *
	 * @return the value of job.effective_time
	 *
	 * @mbggenerated
	 */
	public Date getEffectiveTime() {
		return effectiveTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column job.effective_time
	 *
	 * @param effectiveTime
	 *            the value for job.effective_time
	 *
	 * @mbggenerated
	 */
	public void setEffectiveTime(Date effectiveTime) {
		this.effectiveTime = effectiveTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column job.expiration_time
	 *
	 * @return the value of job.expiration_time
	 *
	 * @mbggenerated
	 */
	public Date getExpirationTime() {
		return expirationTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column job.expiration_time
	 *
	 * @param expirationTime
	 *            the value for job.expiration_time
	 *
	 * @mbggenerated
	 */
	public void setExpirationTime(Date expirationTime) {
		this.expirationTime = expirationTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column job.wage
	 *
	 * @return the value of job.wage
	 *
	 * @mbggenerated
	 */
	public Integer getWage() {
		return wage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column job.wage
	 *
	 * @param wage
	 *            the value for job.wage
	 *
	 * @mbggenerated
	 */
	public void setWage(Integer wage) {
		this.wage = wage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column job.people_number
	 *
	 * @return the value of job.people_number
	 *
	 * @mbggenerated
	 */
	public Integer getPeopleNumber() {
		return peopleNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column job.people_number
	 *
	 * @param peopleNumber
	 *            the value for job.people_number
	 *
	 * @mbggenerated
	 */
	public void setPeopleNumber(Integer peopleNumber) {
		this.peopleNumber = peopleNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column job.education
	 *
	 * @return the value of job.education
	 *
	 * @mbggenerated
	 */
	public String getEducation() {
		return education;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column job.education
	 *
	 * @param education
	 *            the value for job.education
	 *
	 * @mbggenerated
	 */
	public void setEducation(String education) {
		this.education = education == null ? null : education.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column job.service_year
	 *
	 * @return the value of job.service_year
	 *
	 * @mbggenerated
	 */
	public String getServiceYear() {
		return serviceYear;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column job.service_year
	 *
	 * @param serviceYear
	 *            the value for job.service_year
	 *
	 * @mbggenerated
	 */
	public void setServiceYear(String serviceYear) {
		this.serviceYear = serviceYear == null ? null : serviceYear.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column job.description
	 *
	 * @return the value of job.description
	 *
	 * @mbggenerated
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column job.description
	 *
	 * @param description
	 *            the value for job.description
	 *
	 * @mbggenerated
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column job.welfare
	 *
	 * @return the value of job.welfare
	 *
	 * @mbggenerated
	 */
	public String getWelfare() {
		return welfare;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column job.welfare
	 *
	 * @param welfare
	 *            the value for job.welfare
	 *
	 * @mbggenerated
	 */
	public void setWelfare(String welfare) {
		this.welfare = welfare == null ? null : welfare.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column job.email
	 *
	 * @return the value of job.email
	 *
	 * @mbggenerated
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column job.email
	 *
	 * @param email
	 *            the value for job.email
	 *
	 * @mbggenerated
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column job.creat_time
	 *
	 * @return the value of job.creat_time
	 *
	 * @mbggenerated
	 */
	public Date getCreatTime() {
		return creatTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column job.creat_time
	 *
	 * @param creatTime
	 *            the value for job.creat_time
	 *
	 * @mbggenerated
	 */
	public void setCreatTime(Date creatTime) {
		this.creatTime = creatTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column job.update_time
	 *
	 * @return the value of job.update_time
	 *
	 * @mbggenerated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column job.update_time
	 *
	 * @param updateTime
	 *            the value for job.update_time
	 *
	 * @mbggenerated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table job
	 *
	 * @mbggenerated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		Job other = (Job) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getEnterpriseId() == null ? other.getEnterpriseId() == null
						: this.getEnterpriseId().equals(other.getEnterpriseId()))
				&& (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
				&& (this.getNature() == null ? other.getNature() == null : this.getNature().equals(other.getNature()))
				&& (this.getIndustryId() == null ? other.getIndustryId() == null
						: this.getIndustryId().equals(other.getIndustryId()))
				&& (this.getZoneId() == null ? other.getZoneId() == null : this.getZoneId().equals(other.getZoneId()))
				&& (this.getAddress() == null ? other.getAddress() == null
						: this.getAddress().equals(other.getAddress()))
				&& (this.getEffectiveTime() == null ? other.getEffectiveTime() == null
						: this.getEffectiveTime().equals(other.getEffectiveTime()))
				&& (this.getExpirationTime() == null ? other.getExpirationTime() == null
						: this.getExpirationTime().equals(other.getExpirationTime()))
				&& (this.getWage() == null ? other.getWage() == null : this.getWage().equals(other.getWage()))
				&& (this.getPeopleNumber() == null ? other.getPeopleNumber() == null
						: this.getPeopleNumber().equals(other.getPeopleNumber()))
				&& (this.getEducation() == null ? other.getEducation() == null
						: this.getEducation().equals(other.getEducation()))
				&& (this.getServiceYear() == null ? other.getServiceYear() == null
						: this.getServiceYear().equals(other.getServiceYear()))
				&& (this.getDescription() == null ? other.getDescription() == null
						: this.getDescription().equals(other.getDescription()))
				&& (this.getWelfare() == null ? other.getWelfare() == null
						: this.getWelfare().equals(other.getWelfare()))
				&& (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
				&& (this.getCreatTime() == null ? other.getCreatTime() == null
						: this.getCreatTime().equals(other.getCreatTime()))
				&& (this.getUpdateTime() == null ? other.getUpdateTime() == null
						: this.getUpdateTime().equals(other.getUpdateTime()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table job
	 *
	 * @mbggenerated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getEnterpriseId() == null) ? 0 : getEnterpriseId().hashCode());
		result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
		result = prime * result + ((getNature() == null) ? 0 : getNature().hashCode());
		result = prime * result + ((getIndustryId() == null) ? 0 : getIndustryId().hashCode());
		result = prime * result + ((getZoneId() == null) ? 0 : getZoneId().hashCode());
		result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
		result = prime * result + ((getEffectiveTime() == null) ? 0 : getEffectiveTime().hashCode());
		result = prime * result + ((getExpirationTime() == null) ? 0 : getExpirationTime().hashCode());
		result = prime * result + ((getWage() == null) ? 0 : getWage().hashCode());
		result = prime * result + ((getPeopleNumber() == null) ? 0 : getPeopleNumber().hashCode());
		result = prime * result + ((getEducation() == null) ? 0 : getEducation().hashCode());
		result = prime * result + ((getServiceYear() == null) ? 0 : getServiceYear().hashCode());
		result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
		result = prime * result + ((getWelfare() == null) ? 0 : getWelfare().hashCode());
		result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
		result = prime * result + ((getCreatTime() == null) ? 0 : getCreatTime().hashCode());
		result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table job
	 *
	 * @mbggenerated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", enterpriseId=").append(enterpriseId);
		sb.append(", title=").append(title);
		sb.append(", nature=").append(nature);
		sb.append(", industryId=").append(industryId);
		sb.append(", zoneId=").append(zoneId);
		sb.append(", address=").append(address);
		sb.append(", effectiveTime=").append(effectiveTime);
		sb.append(", expirationTime=").append(expirationTime);
		sb.append(", wage=").append(wage);
		sb.append(", peopleNumber=").append(peopleNumber);
		sb.append(", education=").append(education);
		sb.append(", serviceYear=").append(serviceYear);
		sb.append(", description=").append(description);
		sb.append(", welfare=").append(welfare);
		sb.append(", email=").append(email);
		sb.append(", creatTime=").append(creatTime);
		sb.append(", updateTime=").append(updateTime);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}