package com.yiguo.bean;

import java.io.Serializable;
import java.util.Date;

/**
 * 
 * News的实体类
 * 
 * @author liyue
 * @date 2018-01-23
 */
public class News implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column news.id
	 *
	 * @mbggenerated
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column news.title
	 *
	 * @mbggenerated
	 */
	private String title;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column news.abstruct
	 *
	 * @mbggenerated
	 */
	private String abstruct;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column news.main_image
	 *
	 * @mbggenerated
	 */
	private String mainImage;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column news.time
	 *
	 * @mbggenerated
	 */
	private Date time;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column news.start_time
	 *
	 * @mbggenerated
	 */
	private Date startTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column news.end_time
	 *
	 * @mbggenerated
	 */
	private Date endTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column news.create_time
	 *
	 * @mbggenerated
	 */
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column news.update_time
	 *
	 * @mbggenerated
	 */
	private Date updateTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column news.context
	 *
	 * @mbggenerated
	 */
	private String context;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table news
	 *
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column news.id
	 *
	 * @return the value of news.id
	 *
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column news.id
	 *
	 * @param id
	 *            the value for news.id
	 *
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column news.title
	 *
	 * @return the value of news.title
	 *
	 * @mbggenerated
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column news.title
	 *
	 * @param title
	 *            the value for news.title
	 *
	 * @mbggenerated
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column news.abstruct
	 *
	 * @return the value of news.abstruct
	 *
	 * @mbggenerated
	 */
	public String getAbstruct() {
		return abstruct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column news.abstruct
	 *
	 * @param abstruct
	 *            the value for news.abstruct
	 *
	 * @mbggenerated
	 */
	public void setAbstruct(String abstruct) {
		this.abstruct = abstruct == null ? null : abstruct.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column news.main_image
	 *
	 * @return the value of news.main_image
	 *
	 * @mbggenerated
	 */
	public String getMainImage() {
		return mainImage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column news.main_image
	 *
	 * @param mainImage
	 *            the value for news.main_image
	 *
	 * @mbggenerated
	 */
	public void setMainImage(String mainImage) {
		this.mainImage = mainImage == null ? null : mainImage.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column news.time
	 *
	 * @return the value of news.time
	 *
	 * @mbggenerated
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column news.time
	 *
	 * @param time
	 *            the value for news.time
	 *
	 * @mbggenerated
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column news.start_time
	 *
	 * @return the value of news.start_time
	 *
	 * @mbggenerated
	 */
	public Date getStartTime() {
		return startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column news.start_time
	 *
	 * @param startTime
	 *            the value for news.start_time
	 *
	 * @mbggenerated
	 */
	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column news.end_time
	 *
	 * @return the value of news.end_time
	 *
	 * @mbggenerated
	 */
	public Date getEndTime() {
		return endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column news.end_time
	 *
	 * @param endTime
	 *            the value for news.end_time
	 *
	 * @mbggenerated
	 */
	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column news.create_time
	 *
	 * @return the value of news.create_time
	 *
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column news.create_time
	 *
	 * @param createTime
	 *            the value for news.create_time
	 *
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column news.update_time
	 *
	 * @return the value of news.update_time
	 *
	 * @mbggenerated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column news.update_time
	 *
	 * @param updateTime
	 *            the value for news.update_time
	 *
	 * @mbggenerated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column news.context
	 *
	 * @return the value of news.context
	 *
	 * @mbggenerated
	 */
	public String getContext() {
		return context;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column news.context
	 *
	 * @param context
	 *            the value for news.context
	 *
	 * @mbggenerated
	 */
	public void setContext(String context) {
		this.context = context == null ? null : context.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table news
	 *
	 * @mbggenerated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		News other = (News) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
				&& (this.getAbstruct() == null ? other.getAbstruct() == null
						: this.getAbstruct().equals(other.getAbstruct()))
				&& (this.getMainImage() == null ? other.getMainImage() == null
						: this.getMainImage().equals(other.getMainImage()))
				&& (this.getTime() == null ? other.getTime() == null : this.getTime().equals(other.getTime()))
				&& (this.getStartTime() == null ? other.getStartTime() == null
						: this.getStartTime().equals(other.getStartTime()))
				&& (this.getEndTime() == null ? other.getEndTime() == null
						: this.getEndTime().equals(other.getEndTime()))
				&& (this.getCreateTime() == null ? other.getCreateTime() == null
						: this.getCreateTime().equals(other.getCreateTime()))
				&& (this.getUpdateTime() == null ? other.getUpdateTime() == null
						: this.getUpdateTime().equals(other.getUpdateTime()))
				&& (this.getContext() == null ? other.getContext() == null
						: this.getContext().equals(other.getContext()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table news
	 *
	 * @mbggenerated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
		result = prime * result + ((getAbstruct() == null) ? 0 : getAbstruct().hashCode());
		result = prime * result + ((getMainImage() == null) ? 0 : getMainImage().hashCode());
		result = prime * result + ((getTime() == null) ? 0 : getTime().hashCode());
		result = prime * result + ((getStartTime() == null) ? 0 : getStartTime().hashCode());
		result = prime * result + ((getEndTime() == null) ? 0 : getEndTime().hashCode());
		result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
		result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
		result = prime * result + ((getContext() == null) ? 0 : getContext().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table news
	 *
	 * @mbggenerated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", title=").append(title);
		sb.append(", abstruct=").append(abstruct);
		sb.append(", mainImage=").append(mainImage);
		sb.append(", time=").append(time);
		sb.append(", startTime=").append(startTime);
		sb.append(", endTime=").append(endTime);
		sb.append(", createTime=").append(createTime);
		sb.append(", updateTime=").append(updateTime);
		sb.append(", context=").append(context);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}