package com.yiguo.bean;

import java.io.Serializable;
import java.util.Date;

/**
 * 
 * Notification的实体类
 * 
 * @author liyue
 * @date 2018-01-23
 */
public class Notification implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column notification.id
	 *
	 * @mbggenerated
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column notification.title
	 *
	 * @mbggenerated
	 */
	private String title;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column notification.send_time
	 *
	 * @mbggenerated
	 */
	private Date sendTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column notification.context
	 *
	 * @mbggenerated
	 */
	private String context;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column notification.sender_id
	 *
	 * @mbggenerated
	 */
	private Integer senderId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column notification.reciever_id
	 *
	 * @mbggenerated
	 */
	private Integer recieverId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column notification.type
	 *
	 * @mbggenerated
	 */
	private Byte type;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column notification.create_time
	 *
	 * @mbggenerated
	 */
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column notification.update_time
	 *
	 * @mbggenerated
	 */
	private Date updateTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table notification
	 *
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column notification.id
	 *
	 * @return the value of notification.id
	 *
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column notification.id
	 *
	 * @param id
	 *            the value for notification.id
	 *
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column notification.title
	 *
	 * @return the value of notification.title
	 *
	 * @mbggenerated
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column notification.title
	 *
	 * @param title
	 *            the value for notification.title
	 *
	 * @mbggenerated
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column notification.send_time
	 *
	 * @return the value of notification.send_time
	 *
	 * @mbggenerated
	 */
	public Date getSendTime() {
		return sendTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column notification.send_time
	 *
	 * @param sendTime
	 *            the value for notification.send_time
	 *
	 * @mbggenerated
	 */
	public void setSendTime(Date sendTime) {
		this.sendTime = sendTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column notification.context
	 *
	 * @return the value of notification.context
	 *
	 * @mbggenerated
	 */
	public String getContext() {
		return context;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column notification.context
	 *
	 * @param context
	 *            the value for notification.context
	 *
	 * @mbggenerated
	 */
	public void setContext(String context) {
		this.context = context == null ? null : context.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column notification.sender_id
	 *
	 * @return the value of notification.sender_id
	 *
	 * @mbggenerated
	 */
	public Integer getSenderId() {
		return senderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column notification.sender_id
	 *
	 * @param senderId
	 *            the value for notification.sender_id
	 *
	 * @mbggenerated
	 */
	public void setSenderId(Integer senderId) {
		this.senderId = senderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column notification.reciever_id
	 *
	 * @return the value of notification.reciever_id
	 *
	 * @mbggenerated
	 */
	public Integer getRecieverId() {
		return recieverId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column notification.reciever_id
	 *
	 * @param recieverId
	 *            the value for notification.reciever_id
	 *
	 * @mbggenerated
	 */
	public void setRecieverId(Integer recieverId) {
		this.recieverId = recieverId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column notification.type
	 *
	 * @return the value of notification.type
	 *
	 * @mbggenerated
	 */
	public Byte getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column notification.type
	 *
	 * @param type
	 *            the value for notification.type
	 *
	 * @mbggenerated
	 */
	public void setType(Byte type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column notification.create_time
	 *
	 * @return the value of notification.create_time
	 *
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column notification.create_time
	 *
	 * @param createTime
	 *            the value for notification.create_time
	 *
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column notification.update_time
	 *
	 * @return the value of notification.update_time
	 *
	 * @mbggenerated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column notification.update_time
	 *
	 * @param updateTime
	 *            the value for notification.update_time
	 *
	 * @mbggenerated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table notification
	 *
	 * @mbggenerated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		Notification other = (Notification) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
				&& (this.getSendTime() == null ? other.getSendTime() == null
						: this.getSendTime().equals(other.getSendTime()))
				&& (this.getContext() == null ? other.getContext() == null
						: this.getContext().equals(other.getContext()))
				&& (this.getSenderId() == null ? other.getSenderId() == null
						: this.getSenderId().equals(other.getSenderId()))
				&& (this.getRecieverId() == null ? other.getRecieverId() == null
						: this.getRecieverId().equals(other.getRecieverId()))
				&& (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
				&& (this.getCreateTime() == null ? other.getCreateTime() == null
						: this.getCreateTime().equals(other.getCreateTime()))
				&& (this.getUpdateTime() == null ? other.getUpdateTime() == null
						: this.getUpdateTime().equals(other.getUpdateTime()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table notification
	 *
	 * @mbggenerated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
		result = prime * result + ((getSendTime() == null) ? 0 : getSendTime().hashCode());
		result = prime * result + ((getContext() == null) ? 0 : getContext().hashCode());
		result = prime * result + ((getSenderId() == null) ? 0 : getSenderId().hashCode());
		result = prime * result + ((getRecieverId() == null) ? 0 : getRecieverId().hashCode());
		result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
		result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
		result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table notification
	 *
	 * @mbggenerated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", title=").append(title);
		sb.append(", sendTime=").append(sendTime);
		sb.append(", context=").append(context);
		sb.append(", senderId=").append(senderId);
		sb.append(", recieverId=").append(recieverId);
		sb.append(", type=").append(type);
		sb.append(", createTime=").append(createTime);
		sb.append(", updateTime=").append(updateTime);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}