package com.yiguo.bean;

import java.io.Serializable;
import java.util.Date;

/**
 * 
 * resume的实体类
 * 
 * @author liyue
 * @date 2018-01-23
 */
public class Resume implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column resume.id
	 *
	 * @mbggenerated
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column resume.user_id
	 *
	 * @mbggenerated
	 */
	private Integer userId;
    private Integer age;

	public Integer getAge() {
		return age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column resume.user_name
	 *
	 * @mbggenerated
	 */
	private String userName;
	private String resumeLink;

	public String getResumeLink() {
		return resumeLink;
	}

	public void setResumeLink(String resumeLink) {
		this.resumeLink = resumeLink;
	}

	/**

	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column resume.sex
	 *
	 * @mbggenerated
	 */
	private Byte sex;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column resume.telephone
	 *
	 * @mbggenerated
	 */
	private Integer telephone;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column resume.native_place
	 *
	 * @mbggenerated
	 */
	private String nativePlace;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column resume.person_photo
	 *
	 * @mbggenerated
	 */
	private String personPhoto;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column resume.communication_address
	 *
	 * @mbggenerated
	 */
	private String communicationAddress;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column resume.email
	 *
	 * @mbggenerated
	 */
	private String email;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column resume.graduated_school
	 *
	 * @mbggenerated
	 */
	private String graduatedSchool;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column resume.profession
	 *
	 * @mbggenerated
	 */
	private String profession;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column resume.education
	 *
	 * @mbggenerated
	 */
	private String education;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column resume.major_course
	 *
	 * @mbggenerated
	 */
	private String majorCourse;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column resume.score_rank
	 *
	 * @mbggenerated
	 */
	private Byte scoreRank;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column resume.professinal_skill
	 *
	 * @mbggenerated
	 */
	private String professinalSkill;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column resume.reward
	 *
	 * @mbggenerated
	 */
	private String reward;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column resume.self_evaluation
	 *
	 * @mbggenerated
	 */
	private String selfEvaluation;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column resume.create_time
	 *
	 * @mbggenerated
	 */
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column resume.update_time
	 *
	 * @mbggenerated
	 */
	private Date updateTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table resume
	 *
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column resume.id
	 *
	 * @return the value of resume.id
	 *
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column resume.id
	 *
	 * @param id
	 *            the value for resume.id
	 *
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column resume.user_id
	 *
	 * @return the value of resume.user_id
	 *
	 * @mbggenerated
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column resume.user_id
	 *
	 * @param userId
	 *            the value for resume.user_id
	 *
	 * @mbggenerated
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column resume.user_name
	 *
	 * @return the value of resume.user_name
	 *
	 * @mbggenerated
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column resume.user_name
	 *
	 * @param userName
	 *            the value for resume.user_name
	 *
	 * @mbggenerated
	 */
	public void setUserName(String userName) {
		this.userName = userName == null ? null : userName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column resume.sex
	 *
	 * @return the value of resume.sex
	 *
	 * @mbggenerated
	 */
	public Byte getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column resume.sex
	 *
	 * @param sex
	 *            the value for resume.sex
	 *
	 * @mbggenerated
	 */
	public void setSex(Byte sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column resume.telephone
	 *
	 * @return the value of resume.telephone
	 *
	 * @mbggenerated
	 */
	public Integer getTelephone() {
		return telephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column resume.telephone
	 *
	 * @param telephone
	 *            the value for resume.telephone
	 *
	 * @mbggenerated
	 */
	public void setTelephone(Integer telephone) {
		this.telephone = telephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column resume.native_place
	 *
	 * @return the value of resume.native_place
	 *
	 * @mbggenerated
	 */
	public String getNativePlace() {
		return nativePlace;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column resume.native_place
	 *
	 * @param nativePlace
	 *            the value for resume.native_place
	 *
	 * @mbggenerated
	 */
	public void setNativePlace(String nativePlace) {
		this.nativePlace = nativePlace == null ? null : nativePlace.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column resume.person_photo
	 *
	 * @return the value of resume.person_photo
	 *
	 * @mbggenerated
	 */
	public String getPersonPhoto() {
		return personPhoto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column resume.person_photo
	 *
	 * @param personPhoto
	 *            the value for resume.person_photo
	 *
	 * @mbggenerated
	 */
	public void setPersonPhoto(String personPhoto) {
		this.personPhoto = personPhoto == null ? null : personPhoto.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column resume.communication_address
	 *
	 * @return the value of resume.communication_address
	 *
	 * @mbggenerated
	 */
	public String getCommunicationAddress() {
		return communicationAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column resume.communication_address
	 *
	 * @param communicationAddress
	 *            the value for resume.communication_address
	 *
	 * @mbggenerated
	 */
	public void setCommunicationAddress(String communicationAddress) {
		this.communicationAddress = communicationAddress == null ? null : communicationAddress.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column resume.email
	 *
	 * @return the value of resume.email
	 *
	 * @mbggenerated
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column resume.email
	 *
	 * @param email
	 *            the value for resume.email
	 *
	 * @mbggenerated
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column resume.graduated_school
	 *
	 * @return the value of resume.graduated_school
	 *
	 * @mbggenerated
	 */
	public String getGraduatedSchool() {
		return graduatedSchool;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column resume.graduated_school
	 *
	 * @param graduatedSchool
	 *            the value for resume.graduated_school
	 *
	 * @mbggenerated
	 */
	public void setGraduatedSchool(String graduatedSchool) {
		this.graduatedSchool = graduatedSchool == null ? null : graduatedSchool.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column resume.profession
	 *
	 * @return the value of resume.profession
	 *
	 * @mbggenerated
	 */
	public String getProfession() {
		return profession;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column resume.profession
	 *
	 * @param profession
	 *            the value for resume.profession
	 *
	 * @mbggenerated
	 */
	public void setProfession(String profession) {
		this.profession = profession == null ? null : profession.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column resume.education
	 *
	 * @return the value of resume.education
	 *
	 * @mbggenerated
	 */
	public String getEducation() {
		return education;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column resume.education
	 *
	 * @param education
	 *            the value for resume.education
	 *
	 * @mbggenerated
	 */
	public void setEducation(String education) {
		this.education = education == null ? null : education.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column resume.major_course
	 *
	 * @return the value of resume.major_course
	 *
	 * @mbggenerated
	 */
	public String getMajorCourse() {
		return majorCourse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column resume.major_course
	 *
	 * @param majorCourse
	 *            the value for resume.major_course
	 *
	 * @mbggenerated
	 */
	public void setMajorCourse(String majorCourse) {
		this.majorCourse = majorCourse == null ? null : majorCourse.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column resume.score_rank
	 *
	 * @return the value of resume.score_rank
	 *
	 * @mbggenerated
	 */
	public Byte getScoreRank() {
		return scoreRank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column resume.score_rank
	 *
	 * @param scoreRank
	 *            the value for resume.score_rank
	 *
	 * @mbggenerated
	 */
	public void setScoreRank(Byte scoreRank) {
		this.scoreRank = scoreRank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column resume.professinal_skill
	 *
	 * @return the value of resume.professinal_skill
	 *
	 * @mbggenerated
	 */
	public String getProfessinalSkill() {
		return professinalSkill;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column resume.professinal_skill
	 *
	 * @param professinalSkill
	 *            the value for resume.professinal_skill
	 *
	 * @mbggenerated
	 */
	public void setProfessinalSkill(String professinalSkill) {
		this.professinalSkill = professinalSkill == null ? null : professinalSkill.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column resume.reward
	 *
	 * @return the value of resume.reward
	 *
	 * @mbggenerated
	 */
	public String getReward() {
		return reward;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column resume.reward
	 *
	 * @param reward
	 *            the value for resume.reward
	 *
	 * @mbggenerated
	 */
	public void setReward(String reward) {
		this.reward = reward == null ? null : reward.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column resume.self_evaluation
	 *
	 * @return the value of resume.self_evaluation
	 *
	 * @mbggenerated
	 */
	public String getSelfEvaluation() {
		return selfEvaluation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column resume.self_evaluation
	 *
	 * @param selfEvaluation
	 *            the value for resume.self_evaluation
	 *
	 * @mbggenerated
	 */
	public void setSelfEvaluation(String selfEvaluation) {
		this.selfEvaluation = selfEvaluation == null ? null : selfEvaluation.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column resume.create_time
	 *
	 * @return the value of resume.create_time
	 *
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column resume.create_time
	 *
	 * @param createTime
	 *            the value for resume.create_time
	 *
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column resume.update_time
	 *
	 * @return the value of resume.update_time
	 *
	 * @mbggenerated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column resume.update_time
	 *
	 * @param updateTime
	 *            the value for resume.update_time
	 *
	 * @mbggenerated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table resume
	 *
	 * @mbggenerated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		Resume other = (Resume) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
				&& (this.getUserName() == null ? other.getUserName() == null
						: this.getUserName().equals(other.getUserName()))
				&& (this.getSex() == null ? other.getSex() == null : this.getSex().equals(other.getSex()))
				&& (this.getTelephone() == null ? other.getTelephone() == null
						: this.getTelephone().equals(other.getTelephone()))
				&& (this.getNativePlace() == null ? other.getNativePlace() == null
						: this.getNativePlace().equals(other.getNativePlace()))
				&& (this.getPersonPhoto() == null ? other.getPersonPhoto() == null
						: this.getPersonPhoto().equals(other.getPersonPhoto()))
				&& (this.getCommunicationAddress() == null ? other.getCommunicationAddress() == null
						: this.getCommunicationAddress().equals(other.getCommunicationAddress()))
				&& (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
				&& (this.getGraduatedSchool() == null ? other.getGraduatedSchool() == null
						: this.getGraduatedSchool().equals(other.getGraduatedSchool()))
				&& (this.getProfession() == null ? other.getProfession() == null
						: this.getProfession().equals(other.getProfession()))
				&& (this.getEducation() == null ? other.getEducation() == null
						: this.getEducation().equals(other.getEducation()))
				&& (this.getMajorCourse() == null ? other.getMajorCourse() == null
						: this.getMajorCourse().equals(other.getMajorCourse()))
				&& (this.getScoreRank() == null ? other.getScoreRank() == null
						: this.getScoreRank().equals(other.getScoreRank()))
				&& (this.getProfessinalSkill() == null ? other.getProfessinalSkill() == null
						: this.getProfessinalSkill().equals(other.getProfessinalSkill()))
				&& (this.getReward() == null ? other.getReward() == null : this.getReward().equals(other.getReward()))
				&& (this.getSelfEvaluation() == null ? other.getSelfEvaluation() == null
						: this.getSelfEvaluation().equals(other.getSelfEvaluation()))
				&& (this.getCreateTime() == null ? other.getCreateTime() == null
						: this.getCreateTime().equals(other.getCreateTime()))
				&& (this.getUpdateTime() == null ? other.getUpdateTime() == null
						: this.getUpdateTime().equals(other.getUpdateTime()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table resume
	 *
	 * @mbggenerated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
		result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
		result = prime * result + ((getSex() == null) ? 0 : getSex().hashCode());
		result = prime * result + ((getTelephone() == null) ? 0 : getTelephone().hashCode());
		result = prime * result + ((getNativePlace() == null) ? 0 : getNativePlace().hashCode());
		result = prime * result + ((getPersonPhoto() == null) ? 0 : getPersonPhoto().hashCode());
		result = prime * result + ((getCommunicationAddress() == null) ? 0 : getCommunicationAddress().hashCode());
		result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
		result = prime * result + ((getGraduatedSchool() == null) ? 0 : getGraduatedSchool().hashCode());
		result = prime * result + ((getProfession() == null) ? 0 : getProfession().hashCode());
		result = prime * result + ((getEducation() == null) ? 0 : getEducation().hashCode());
		result = prime * result + ((getMajorCourse() == null) ? 0 : getMajorCourse().hashCode());
		result = prime * result + ((getScoreRank() == null) ? 0 : getScoreRank().hashCode());
		result = prime * result + ((getProfessinalSkill() == null) ? 0 : getProfessinalSkill().hashCode());
		result = prime * result + ((getReward() == null) ? 0 : getReward().hashCode());
		result = prime * result + ((getSelfEvaluation() == null) ? 0 : getSelfEvaluation().hashCode());
		result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
		result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table resume
	 *
	 * @mbggenerated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", userId=").append(userId);
		sb.append(", userName=").append(userName);
		sb.append(", sex=").append(sex);
		sb.append(", telephone=").append(telephone);
		sb.append(", nativePlace=").append(nativePlace);
		sb.append(", personPhoto=").append(personPhoto);
		sb.append(", communicationAddress=").append(communicationAddress);
		sb.append(", email=").append(email);
		sb.append(", graduatedSchool=").append(graduatedSchool);
		sb.append(", profession=").append(profession);
		sb.append(", education=").append(education);
		sb.append(", majorCourse=").append(majorCourse);
		sb.append(", scoreRank=").append(scoreRank);
		sb.append(", professinalSkill=").append(professinalSkill);
		sb.append(", reward=").append(reward);
		sb.append(", selfEvaluation=").append(selfEvaluation);
		sb.append(", createTime=").append(createTime);
		sb.append(", updateTime=").append(updateTime);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}