package com.yiguo.bean;

import java.io.Serializable;
import java.util.Date;

/**
 * 
 * Resume_post_record实体类
 * 
 * @author liyue
 * @date 2018-01-23
 */
public class Resume_post_record implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column resume_post_record.id
	 *
	 * @mbggenerated
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column resume_post_record.resume_id
	 *
	 * @mbggenerated
	 */
	private Integer resumeId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column resume_post_record.job_id
	 *
	 * @mbggenerated
	 */
	private Integer jobId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column resume_post_record.state
	 *
	 * @mbggenerated
	 */
	private Byte state;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column resume_post_record.create_time
	 *
	 * @mbggenerated
	 */
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column resume_post_record.update_time
	 *
	 * @mbggenerated
	 */
	private Date updateTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table resume_post_record
	 *
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column resume_post_record.id
	 *
	 * @return the value of resume_post_record.id
	 *
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column resume_post_record.id
	 *
	 * @param id
	 *            the value for resume_post_record.id
	 *
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column resume_post_record.resume_id
	 *
	 * @return the value of resume_post_record.resume_id
	 *
	 * @mbggenerated
	 */
	public Integer getResumeId() {
		return resumeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column resume_post_record.resume_id
	 *
	 * @param resumeId
	 *            the value for resume_post_record.resume_id
	 *
	 * @mbggenerated
	 */
	public void setResumeId(Integer resumeId) {
		this.resumeId = resumeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column resume_post_record.job_id
	 *
	 * @return the value of resume_post_record.job_id
	 *
	 * @mbggenerated
	 */
	public Integer getJobId() {
		return jobId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column resume_post_record.job_id
	 *
	 * @param jobId
	 *            the value for resume_post_record.job_id
	 *
	 * @mbggenerated
	 */
	public void setJobId(Integer jobId) {
		this.jobId = jobId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column resume_post_record.state
	 *
	 * @return the value of resume_post_record.state
	 *
	 * @mbggenerated
	 */
	public Byte getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column resume_post_record.state
	 *
	 * @param state
	 *            the value for resume_post_record.state
	 *
	 * @mbggenerated
	 */
	public void setState(Byte state) {
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column resume_post_record.create_time
	 *
	 * @return the value of resume_post_record.create_time
	 *
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column resume_post_record.create_time
	 *
	 * @param createTime
	 *            the value for resume_post_record.create_time
	 *
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column resume_post_record.update_time
	 *
	 * @return the value of resume_post_record.update_time
	 *
	 * @mbggenerated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column resume_post_record.update_time
	 *
	 * @param updateTime
	 *            the value for resume_post_record.update_time
	 *
	 * @mbggenerated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table resume_post_record
	 *
	 * @mbggenerated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		Resume_post_record other = (Resume_post_record) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getResumeId() == null ? other.getResumeId() == null
						: this.getResumeId().equals(other.getResumeId()))
				&& (this.getJobId() == null ? other.getJobId() == null : this.getJobId().equals(other.getJobId()))
				&& (this.getState() == null ? other.getState() == null : this.getState().equals(other.getState()))
				&& (this.getCreateTime() == null ? other.getCreateTime() == null
						: this.getCreateTime().equals(other.getCreateTime()))
				&& (this.getUpdateTime() == null ? other.getUpdateTime() == null
						: this.getUpdateTime().equals(other.getUpdateTime()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table resume_post_record
	 *
	 * @mbggenerated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getResumeId() == null) ? 0 : getResumeId().hashCode());
		result = prime * result + ((getJobId() == null) ? 0 : getJobId().hashCode());
		result = prime * result + ((getState() == null) ? 0 : getState().hashCode());
		result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
		result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table resume_post_record
	 *
	 * @mbggenerated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", resumeId=").append(resumeId);
		sb.append(", jobId=").append(jobId);
		sb.append(", state=").append(state);
		sb.append(", createTime=").append(createTime);
		sb.append(", updateTime=").append(updateTime);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}