package com.yiguo.bean;

import java.io.Serializable;
import java.util.Date;

/**
 * 
 * School的实体类
 * 
 * @author liyue
 * @date 2018-01-23
 */
public class School implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column school.id
	 *
	 * @mbggenerated
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column school.name
	 *
	 * @mbggenerated
	 */
	private String name;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column school.zone_id
	 *
	 * @mbggenerated
	 */
	private Integer zoneId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column school.type
	 *
	 * @mbggenerated
	 */
	private String type;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column school.properties
	 *
	 * @mbggenerated
	 */
	private String properties;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column school.create_time
	 *
	 * @mbggenerated
	 */
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column school.update_time
	 *
	 * @mbggenerated
	 */
	private Date updateTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table school
	 *
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column school.id
	 *
	 * @return the value of school.id
	 *
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column school.id
	 *
	 * @param id
	 *            the value for school.id
	 *
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column school.name
	 *
	 * @return the value of school.name
	 *
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column school.name
	 *
	 * @param name
	 *            the value for school.name
	 *
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column school.zone_id
	 *
	 * @return the value of school.zone_id
	 *
	 * @mbggenerated
	 */
	public Integer getZoneId() {
		return zoneId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column school.zone_id
	 *
	 * @param zoneId
	 *            the value for school.zone_id
	 *
	 * @mbggenerated
	 */
	public void setZoneId(Integer zoneId) {
		this.zoneId = zoneId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column school.type
	 *
	 * @return the value of school.type
	 *
	 * @mbggenerated
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column school.type
	 *
	 * @param type
	 *            the value for school.type
	 *
	 * @mbggenerated
	 */
	public void setType(String type) {
		this.type = type == null ? null : type.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column school.properties
	 *
	 * @return the value of school.properties
	 *
	 * @mbggenerated
	 */
	public String getProperties() {
		return properties;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column school.properties
	 *
	 * @param properties
	 *            the value for school.properties
	 *
	 * @mbggenerated
	 */
	public void setProperties(String properties) {
		this.properties = properties == null ? null : properties.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column school.create_time
	 *
	 * @return the value of school.create_time
	 *
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column school.create_time
	 *
	 * @param createTime
	 *            the value for school.create_time
	 *
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column school.update_time
	 *
	 * @return the value of school.update_time
	 *
	 * @mbggenerated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column school.update_time
	 *
	 * @param updateTime
	 *            the value for school.update_time
	 *
	 * @mbggenerated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table school
	 *
	 * @mbggenerated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		School other = (School) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
				&& (this.getZoneId() == null ? other.getZoneId() == null : this.getZoneId().equals(other.getZoneId()))
				&& (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
				&& (this.getProperties() == null ? other.getProperties() == null
						: this.getProperties().equals(other.getProperties()))
				&& (this.getCreateTime() == null ? other.getCreateTime() == null
						: this.getCreateTime().equals(other.getCreateTime()))
				&& (this.getUpdateTime() == null ? other.getUpdateTime() == null
						: this.getUpdateTime().equals(other.getUpdateTime()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table school
	 *
	 * @mbggenerated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
		result = prime * result + ((getZoneId() == null) ? 0 : getZoneId().hashCode());
		result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
		result = prime * result + ((getProperties() == null) ? 0 : getProperties().hashCode());
		result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
		result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table school
	 *
	 * @mbggenerated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", name=").append(name);
		sb.append(", zoneId=").append(zoneId);
		sb.append(", type=").append(type);
		sb.append(", properties=").append(properties);
		sb.append(", createTime=").append(createTime);
		sb.append(", updateTime=").append(updateTime);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}